domain_path: C:\Projects\SWHW\HardwareSoftwareCodesign\Vitis_Project\soc_platform\zynq_fsbl\zynq_fsbl_bsp
app_src_dir: C:\Xilinx\2025.1\Vitis\data\embeddedsw\lib\sw_apps\zynq_fsbl
template: zynq_fsbl
lang: c
