# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.srcs/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/soc_design_axi_smc_0.xci
# IP: The module: 'soc_design_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/bd_404a.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_0/bd_404a_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_1/bd_404a_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_2/bd_404a_arinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_3/bd_404a_rinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_4/bd_404a_awinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_5/bd_404a_winsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_6/bd_404a_binsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_7/bd_404a_aroutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_8/bd_404a_routsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_9/bd_404a_awoutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_10/bd_404a_woutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_11/bd_404a_boutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_12/bd_404a_arni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_13/bd_404a_rni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_14/bd_404a_awni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_15/bd_404a_wni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_16/bd_404a_bni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_17/bd_404a_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_18/bd_404a_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_19/bd_404a_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_20/bd_404a_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_21/bd_404a_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_22/bd_404a_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_23/bd_404a_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_24/bd_404a_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_25/bd_404a_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_26/bd_404a_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_27/bd_404a_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_28/bd_404a_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_29/bd_404a_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_30/bd_404a_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_31/bd_404a_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_32/bd_404a_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_33/bd_404a_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_34/bd_404a_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_35/bd_404a_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_36/bd_404a_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_37/bd_404a_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_38/bd_404a_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_39/bd_404a_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_1/bd_404a_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_2/bd_404a_arinsw_0_ooc.xdc

# XDC: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_3/bd_404a_rinsw_0_ooc.xdc

# XDC: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_4/bd_404a_awinsw_0_ooc.xdc

# XDC: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_5/bd_404a_winsw_0_ooc.xdc

# XDC: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_6/bd_404a_binsw_0_ooc.xdc

# XDC: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_7/bd_404a_aroutsw_0_ooc.xdc

# XDC: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_8/bd_404a_routsw_0_ooc.xdc

# XDC: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_9/bd_404a_awoutsw_0_ooc.xdc

# XDC: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_10/bd_404a_woutsw_0_ooc.xdc

# XDC: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_11/bd_404a_boutsw_0_ooc.xdc

# XDC: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_12/bd_404a_arni_0_ooc.xdc

# XDC: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_13/bd_404a_rni_0_ooc.xdc

# XDC: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_14/bd_404a_awni_0_ooc.xdc

# XDC: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_15/bd_404a_wni_0_ooc.xdc

# XDC: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_16/bd_404a_bni_0_ooc.xdc

# XDC: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_20/bd_404a_s00a2s_0_ooc.xdc

# XDC: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_21/bd_404a_sarn_0_ooc.xdc

# XDC: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_22/bd_404a_srn_0_ooc.xdc

# XDC: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_23/bd_404a_sawn_0_ooc.xdc

# XDC: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_24/bd_404a_swn_0_ooc.xdc

# XDC: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_25/bd_404a_sbn_0_ooc.xdc

# XDC: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_26/bd_404a_m00s2a_0_ooc.xdc

# XDC: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_27/bd_404a_m00arn_0_ooc.xdc

# XDC: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_28/bd_404a_m00rn_0_ooc.xdc

# XDC: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_29/bd_404a_m00awn_0_ooc.xdc

# XDC: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_30/bd_404a_m00wn_0_ooc.xdc

# XDC: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_31/bd_404a_m00bn_0_ooc.xdc

# XDC: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_33/bd_404a_m01s2a_0_ooc.xdc

# XDC: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_34/bd_404a_m01arn_0_ooc.xdc

# XDC: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_35/bd_404a_m01rn_0_ooc.xdc

# XDC: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_36/bd_404a_m01awn_0_ooc.xdc

# XDC: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_37/bd_404a_m01wn_0_ooc.xdc

# XDC: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_38/bd_404a_m01bn_0_ooc.xdc

# XDC: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_design_axi_smc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_design_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.srcs/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/soc_design_axi_smc_0.xci
# IP: The module: 'soc_design_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/bd_404a.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_0/bd_404a_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_1/bd_404a_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_2/bd_404a_arinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_3/bd_404a_rinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_4/bd_404a_awinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_5/bd_404a_winsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_6/bd_404a_binsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_7/bd_404a_aroutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_8/bd_404a_routsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_9/bd_404a_awoutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_10/bd_404a_woutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_11/bd_404a_boutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_12/bd_404a_arni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_13/bd_404a_rni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_14/bd_404a_awni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_15/bd_404a_wni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_16/bd_404a_bni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_17/bd_404a_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_18/bd_404a_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_19/bd_404a_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_20/bd_404a_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_21/bd_404a_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_22/bd_404a_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_23/bd_404a_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_24/bd_404a_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_25/bd_404a_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_26/bd_404a_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_27/bd_404a_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_28/bd_404a_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_29/bd_404a_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_30/bd_404a_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_31/bd_404a_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_32/bd_404a_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_33/bd_404a_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_34/bd_404a_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_35/bd_404a_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_36/bd_404a_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_37/bd_404a_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_38/bd_404a_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_39/bd_404a_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_1/bd_404a_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_2/bd_404a_arinsw_0_ooc.xdc

# XDC: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_3/bd_404a_rinsw_0_ooc.xdc

# XDC: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_4/bd_404a_awinsw_0_ooc.xdc

# XDC: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_5/bd_404a_winsw_0_ooc.xdc

# XDC: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_6/bd_404a_binsw_0_ooc.xdc

# XDC: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_7/bd_404a_aroutsw_0_ooc.xdc

# XDC: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_8/bd_404a_routsw_0_ooc.xdc

# XDC: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_9/bd_404a_awoutsw_0_ooc.xdc

# XDC: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_10/bd_404a_woutsw_0_ooc.xdc

# XDC: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_11/bd_404a_boutsw_0_ooc.xdc

# XDC: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_12/bd_404a_arni_0_ooc.xdc

# XDC: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_13/bd_404a_rni_0_ooc.xdc

# XDC: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_14/bd_404a_awni_0_ooc.xdc

# XDC: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_15/bd_404a_wni_0_ooc.xdc

# XDC: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_16/bd_404a_bni_0_ooc.xdc

# XDC: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_20/bd_404a_s00a2s_0_ooc.xdc

# XDC: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_21/bd_404a_sarn_0_ooc.xdc

# XDC: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_22/bd_404a_srn_0_ooc.xdc

# XDC: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_23/bd_404a_sawn_0_ooc.xdc

# XDC: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_24/bd_404a_swn_0_ooc.xdc

# XDC: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_25/bd_404a_sbn_0_ooc.xdc

# XDC: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_26/bd_404a_m00s2a_0_ooc.xdc

# XDC: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_27/bd_404a_m00arn_0_ooc.xdc

# XDC: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_28/bd_404a_m00rn_0_ooc.xdc

# XDC: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_29/bd_404a_m00awn_0_ooc.xdc

# XDC: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_30/bd_404a_m00wn_0_ooc.xdc

# XDC: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_31/bd_404a_m00bn_0_ooc.xdc

# XDC: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_33/bd_404a_m01s2a_0_ooc.xdc

# XDC: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_34/bd_404a_m01arn_0_ooc.xdc

# XDC: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_35/bd_404a_m01rn_0_ooc.xdc

# XDC: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_36/bd_404a_m01awn_0_ooc.xdc

# XDC: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_37/bd_404a_m01wn_0_ooc.xdc

# XDC: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/bd_0/ip/ip_38/bd_404a_m01bn_0_ooc.xdc

# XDC: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_design_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/abdud/Desktop/HWSWCodesign/HardwareSoftwareCodesign/Vivado_Project/SoC_Project/SoC_Project.gen/sources_1/bd/soc_design/ip/soc_design_axi_smc_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_design_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
