# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/soc_design/soc_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_design || ORIG_REF_NAME==soc_design} -quiet] -quiet

# IP: bd/soc_design/ip/soc_design_processing_system7_0_0/soc_design_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_design_processing_system7_0_0 || ORIG_REF_NAME==soc_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/soc_design/ip/soc_design_two_bit_adder_0_0/soc_design_two_bit_adder_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_design_two_bit_adder_0_0 || ORIG_REF_NAME==soc_design_two_bit_adder_0_0} -quiet] -quiet

# IP: bd/soc_design/ip/soc_design_axi_smc_0/soc_design_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_design_axi_smc_0 || ORIG_REF_NAME==soc_design_axi_smc_0} -quiet] -quiet

# IP: bd/soc_design/ip/soc_design_rst_ps7_0_100M_0/soc_design_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_design_rst_ps7_0_100M_0 || ORIG_REF_NAME==soc_design_rst_ps7_0_100M_0} -quiet] -quiet

# XDC: c:/Users/azmib/Desktop/HardwareSoftwareCodesign/Vivado_Project/HWSW_Codesign.gen/sources_1/bd/soc_design/soc_design_ooc.xdc
