# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/default_block_design/default_block_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==default_block_design || ORIG_REF_NAME==default_block_design} -quiet] -quiet

# IP: bd/default_block_design/ip/default_block_design_processing_system7_0_0/default_block_design_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==default_block_design_processing_system7_0_0 || ORIG_REF_NAME==default_block_design_processing_system7_0_0} -quiet] -quiet

# XDC: c:/Projects/HWSW/Vivado Project/test_2/test_2.gen/sources_1/bd/default_block_design/default_block_design_ooc.xdc
