# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Projects/HWSW/Vivado Project/test_2/test_2.srcs/sources_1/bd/default_block_design/ip/default_block_design_processing_system7_0_0/default_block_design_processing_system7_0_0.xci
# IP: The module: 'default_block_design_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Projects/HWSW/Vivado Project/test_2/test_2.gen/sources_1/bd/default_block_design/ip/default_block_design_processing_system7_0_0/default_block_design_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'default_block_design_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Projects/HWSW/Vivado Project/test_2/test_2.srcs/sources_1/bd/default_block_design/ip/default_block_design_processing_system7_0_0/default_block_design_processing_system7_0_0.xci
# IP: The module: 'default_block_design_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Projects/HWSW/Vivado Project/test_2/test_2.gen/sources_1/bd/default_block_design/ip/default_block_design_processing_system7_0_0/default_block_design_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'default_block_design_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
